
import clases.ToothException;
import clases.direction;
import java.awt.Color;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gonzalo
 */
public class addCita extends javax.swing.JDialog {

    /**
     * Creates new form addCita
     */
    public addCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Image/Icono1.png")).getImage());
        conectar();
        m=(DefaultTableModel) tblcitas.getModel();
        jdfecha.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcitas = new javax.swing.JTable();
        btnVerCitas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn173 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn183 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn193 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn113 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn123 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn133 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn203 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn93 = new javax.swing.JButton();
        btn103 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn163 = new javax.swing.JButton();
        txtpaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jdfecha = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ToothCenter - Añadir Cita");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblcitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Descripcion", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcitas);

        btnVerCitas.setBackground(new java.awt.Color(255, 255, 255));
        btnVerCitas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn173.setBackground(new java.awt.Color(255, 255, 255));
        btn173.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn173.setText("17:30");
        btn173.setEnabled(false);
        btn173.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn173ActionPerformed(evt);
            }
        });

        btn17.setBackground(new java.awt.Color(255, 255, 255));
        btn17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn17.setText("17:00");
        btn17.setEnabled(false);
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setBackground(new java.awt.Color(255, 255, 255));
        btn18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn18.setText("18:00");
        btn18.setEnabled(false);
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });

        btn183.setBackground(new java.awt.Color(255, 255, 255));
        btn183.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn183.setText("18:30");
        btn183.setEnabled(false);
        btn183.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn183ActionPerformed(evt);
            }
        });

        btn19.setBackground(new java.awt.Color(255, 255, 255));
        btn19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn19.setText("19:00");
        btn19.setEnabled(false);
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });

        btn193.setBackground(new java.awt.Color(255, 255, 255));
        btn193.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn193.setText("19:30");
        btn193.setEnabled(false);
        btn193.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn193ActionPerformed(evt);
            }
        });

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        btn11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn11.setText("11:00");
        btn11.setEnabled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn113.setBackground(new java.awt.Color(255, 255, 255));
        btn113.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn113.setText("11:30");
        btn113.setEnabled(false);
        btn113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn113ActionPerformed(evt);
            }
        });

        btn12.setBackground(new java.awt.Color(255, 255, 255));
        btn12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn12.setText("12:00");
        btn12.setEnabled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn123.setBackground(new java.awt.Color(255, 255, 255));
        btn123.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn123.setText("12:30");
        btn123.setEnabled(false);
        btn123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn123ActionPerformed(evt);
            }
        });

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        btn13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn13.setText("13:00");
        btn13.setEnabled(false);
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn133.setBackground(new java.awt.Color(255, 255, 255));
        btn133.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn133.setText("13:30");
        btn133.setEnabled(false);
        btn133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn133ActionPerformed(evt);
            }
        });

        btn14.setBackground(new java.awt.Color(255, 255, 255));
        btn14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn14.setText("14:00");
        btn14.setEnabled(false);
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn20.setBackground(new java.awt.Color(255, 255, 255));
        btn20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn20.setText("20:00");
        btn20.setEnabled(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn203.setBackground(new java.awt.Color(255, 255, 255));
        btn203.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn203.setText("20:30");
        btn203.setEnabled(false);
        btn203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn203ActionPerformed(evt);
            }
        });

        btn21.setBackground(new java.awt.Color(255, 255, 255));
        btn21.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn21.setText("21:00");
        btn21.setEnabled(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn9.setText("9:00");
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn93.setBackground(new java.awt.Color(255, 255, 255));
        btn93.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn93.setText("9:30");
        btn93.setEnabled(false);
        btn93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn93ActionPerformed(evt);
            }
        });

        btn103.setBackground(new java.awt.Color(255, 255, 255));
        btn103.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn103.setText("10:30");
        btn103.setEnabled(false);
        btn103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn103ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(255, 255, 255));
        btn10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn10.setText("10:00");
        btn10.setEnabled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn16.setBackground(new java.awt.Color(255, 255, 255));
        btn16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn16.setText("16:00");
        btn16.setEnabled(false);
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn163.setBackground(new java.awt.Color(255, 255, 255));
        btn163.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn163.setText("16:30");
        btn163.setEnabled(false);
        btn163.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn163ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn93, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn103, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn113, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn123, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn133, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn163, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn173, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn183, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn193, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn203, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn10, btn103, btn11, btn113, btn12, btn123, btn13, btn133, btn14, btn16, btn163, btn17, btn173, btn18, btn183, btn19, btn193, btn20, btn203, btn21, btn9, btn93});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn93, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn103, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn113, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn123, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn133, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn163, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn173, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn183, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn193, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn203, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn10, btn103, btn11, btn113, btn12, btn123, btn13, btn133, btn14, btn16, btn163, btn17, btn173, btn18, btn183, btn19, btn193, btn20, btn203, btn21, btn9, btn93});

        txtpaciente.setEditable(false);
        txtpaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtpaciente.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtpaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpacienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion:");

        txtdes.setEditable(false);
        txtdes.setBackground(new java.awt.Color(255, 255, 255));
        txtdes.setColumns(20);
        txtdes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtdes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setText("Paciente:");

        jdfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jdfechaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jmRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jmRegresar.setToolTipText("Atras");
        jmRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRegresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmRegresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void validarFecha(){
        if(jdfecha.getDate() == null){
            jdfecha.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            throw new ToothException("Introduce una fecha");
        }
        Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        mes=mes+1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int d=jdfecha.getDate().getDate();
        int m=jdfecha.getDate().getMonth();
        m=m+1;
        int y=jdfecha.getDate().getYear()+1900;
        //showMessageDialog(this,d+"/"+m+"/"+y+"\n"+dia+"/"+mes+"/"+año);
        if(d==dia&&m==mes&&y<año){
            throw new ToothException("La fecha no puede ser anterior a la actual");
        }else{
            if(d==dia&&m<mes&&y<=año){
                throw new ToothException("La fecha no puede ser anterior a la actual");
            }else{
                if(d>dia&&m<mes&&y<=año){
                    throw new ToothException("La fecha no puede ser anterior a la actual");
                }else{
                    if(d<dia&&m==mes&&y<=año){
                        throw new ToothException("La fecha no puede ser anterior a la actual");
                    }
                }
            }
        }
    }
    
    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        try{
            validarFecha();
            if(validar()==false){
                return;
            }
            fecha=jdfecha.getDate().getDate()+"/"+(jdfecha.getDate().getMonth()+1)+"/"+(jdfecha.getDate().getYear()+1900);
            habilitarbotones();
            llenartabla();
            txtdes.setEditable(true);
        }catch(ToothException e){
            showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnVerCitasActionPerformed

    public void habilitarbotones()
    {
        btn9.setEnabled(true);btn93.setEnabled(true);
        btn10.setEnabled(true);btn103.setEnabled(true);
        btn11.setEnabled(true);btn113.setEnabled(true);
        btn12.setEnabled(true);btn123.setEnabled(true);
        btn13.setEnabled(true);btn133.setEnabled(true);
        btn14.setEnabled(true);
        btn16.setEnabled(true);btn163.setEnabled(true);
        btn17.setEnabled(true);btn173.setEnabled(true);
        btn18.setEnabled(true);btn183.setEnabled(true);
        btn19.setEnabled(true);btn193.setEnabled(true);
        btn20.setEnabled(true);btn203.setEnabled(true);
        btn21.setEnabled(true);
        
    }
    public boolean validar()
    {
        if(jdfecha.getDate()==null)
        {
            showMessageDialog(this,"Selecciona una fecha");
            return false;
        }
        return true;
    }                        
    
    public void insertarcita()
    {
         String cad="";
        try
        {
           Statement stmt=cn.createStatement();
           cad="insert into Citas (Id_p,Paciente,Descripcion,Fecha,Hora) values ("+id+",'"+txtpaciente.getText()+"',"+"'"+txtdes.getText()+"'"+",DateValue('"+fecha+"'),"+"'"+hrcita+"'"+");";
           stmt.executeUpdate(cad);
           stmt.close(); 
           llenartabla();
        }catch(SQLException ex){showMessageDialog(this,"Error");}
    }
    
    private void btn173ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn173ActionPerformed
        try{
            validarFecha();
            hrcita="17:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn173.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn173ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        try{
            validarFecha();
            hrcita="17:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn17.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        try{
            validarFecha();
            hrcita="18:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn18.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn183ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn183ActionPerformed
        try{
            validarFecha();
            hrcita="18:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn183.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn183ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        try{
            validarFecha();
            hrcita="19:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn19.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn193ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn193ActionPerformed
        try{
            validarFecha();
            hrcita="19:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn193.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn193ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        try{
            validarFecha();
            hrcita="11:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendaras una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }else{
                insertarcita();
                btn11.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn113ActionPerformed
        try{
            validarFecha();
            hrcita="11:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }else{
                insertarcita();
                btn113.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn113ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        try{
            validarFecha();
            hrcita="12:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendaras una cita para: "+txtpaciente.getText()+" A las:"+hrcita+" hrs")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn12.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn123ActionPerformed
        try{
            validarFecha();
            hrcita="12:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }else{
                insertarcita();
                btn123.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn123ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        try{
            validarFecha();
            hrcita="13:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendaras una cita para: "+txtpaciente.getText()+" A las:"+hrcita+" hrs")!=0){
                return;
            }else{
                insertarcita();
                btn13.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn133ActionPerformed
        try{
            validarFecha();
            hrcita="13:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }else{
                insertarcita();
                btn133.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn133ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        try{
            validarFecha();
            hrcita="14:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendaras una cita para: "+txtpaciente.getText()+" A las:"+hrcita+" hrs")!=0){
                return;
            }else{
                insertarcita();
                btn14.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        try{
            validarFecha();
            hrcita="20:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn20.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn203ActionPerformed
        try{
            validarFecha();
            hrcita="20:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn203.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn203ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        try{
            validarFecha();
            hrcita="21:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn21.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        try{
            validarFecha();
            hrcita="09:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }else{
                insertarcita();
                btn9.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn93ActionPerformed
        try{
            validarFecha();
            hrcita="09:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendaras una cita para: "+txtpaciente.getText()+" A las:"+hrcita+" hrs")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn93.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn93ActionPerformed

    private void btn103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn103ActionPerformed
        try{
            validarFecha();
            hrcita="10:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn103.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn103ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        try{
            validarFecha();
            hrcita="10:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para: "+txtpaciente.getText()+" A las:"+hrcita+" hrs")!=0){
                return;
            }else{
                insertarcita();
                btn10.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        try{
            validarFecha();
            hrcita="16:00";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0){
                return;
            }
            else{
                insertarcita();
                btn16.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn163ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn163ActionPerformed
        try{
            validarFecha();
            hrcita="16:30";
            if(javax.swing.JOptionPane.showConfirmDialog(rootPane,"Agendarás una cita para "+txtpaciente.getText()+" a las "+hrcita+" hrs.")!=0)
            {
                return;
            }
            else
            {
                insertarcita();
                btn163.setEnabled(false);
            }
        }catch(ToothException e){
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn163ActionPerformed

    public void llenartabla(){
        try{
            Statement stmt=cn.createStatement();
            stmt.execute("select*from Citas where Fecha=DateValue('"+fecha+"')order by Hora;");
            ResultSet rs=stmt.getResultSet();
            m.setRowCount(0);
            Object  O[]=new Object[4];
            if(rs!=null){
                while(rs.next()){    
                    O[0]=rs.getString("paciente");
                    O[1]=rs.getString("descripcion");
                    O[2]=rs.getDate("fecha");
                    O[3]=rs.getString("hora");
                    m.addRow(O);
                }
            }else{
                showMessageDialog(this,"No hay");
            }
            stmt.close();
            consultas();
        }catch(SQLException ex){
            showMessageDialog(this,ex.getMessage());
        }
    }
    public void ordenar(){
        for(int i=0;i<tblcitas.getRowCount();i++){
            int ca=0;
            String cad=tblcitas.getValueAt(i, 4).toString();
            for(int c=0;c<cad.length();c++){
                ca=ca+cad.charAt(c);
            }//for 2
        }//for1
    }
    
    public void consultas(){
        String co;
        for(int i=0;i<m.getRowCount();i++){
            co=m.getValueAt(i,3).toString();
            deshabilita(co);
        }
    }   
    
    public void deshabilita(String i){
            if(i.equals("09:00")){
                btn9.setEnabled(false);
            } else {
                if(i.equals("09:30")){
                    btn93.setEnabled(false);
                } else{
                    if(i.equals("10:00")){
                        btn10.setEnabled(false);
                    }else{
                        if(i.equals("10:30")){
                            btn103.setEnabled(false);
                        }else{
                           if(i.equals("11:00")){
                               btn11.setEnabled(false);
                           }else{
                               if(i.equals("11:30")){
                                   btn113.setEnabled(false);
                                }else{
                                    if(i.equals("12:00")){
                                        btn12.setEnabled(false);
                                    }else{
                                        if(i.equals("12:30")){
                                            btn123.setEnabled(false);
                                        }else{
                                            if(i.equals("13:00")){
                                                btn13.setEnabled(false);
                                            }else{
                                                if(i.equals("13:30")){
                                                    btn133.setEnabled(false);
                                                }else{
                                                    if(i.equals("14:00")){
                                                        btn14.setEnabled(false);
                                                    }else{
                                                        if(i.equals("16:00")){
                                                            btn16.setEnabled(false);
                                                        }else{
                                                            if(i.equals("16:30")){
                                                                btn163.setEnabled(false);
                                                            }else{
                                                                if(i.equals("17:00")){
                                                                    btn17.setEnabled(false);
                                                                }else{
                                                                    if(i.equals("17:30")){
                                                                        btn173.setEnabled(false);
                                                                    }else{
                                                                        if(i.equals("18:00")){
                                                                            btn18.setEnabled(false);
                                                                        }else{
                                                                            if(i.equals("18:30")){
                                                                                btn183.setEnabled(false);
                                                                            }else{
                                                                                if(i.equals("19:00")){
                                                                                    btn19.setEnabled(false);
                                                                                }else{
                                                                                    if(i.equals("19:30")){
                                                                                        btn193.setEnabled(false);
                                                                                    }else{
                                                                                        if(i.equals("20:00")){
                                                                                            btn20.setEnabled(false);
                                                                                        }else{
                                                                                            if(i.equals("20:30")){
                                                                                                btn203.setEnabled(false);
                                                                                            }else{
                                                                                                if(i.equals("21:00")){
                                                                                                    btn21.setEnabled(false);
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
    }
    public void conectar(){
        direction dir = new direction();
        dir.readTxt("C:\\dir.ini");
        String dbURL="jdbc:ucanaccess://"+dir.getDir();
        try {
            cn=DriverManager.getConnection(dbURL,"","");
            System.out.println("Conectado");
        } catch (SQLException ex) {
            Logger.getLogger(nPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpacienteActionPerformed

    private void jdfechaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdfechaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jdfechaMouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtpaciente.setText(paciente);
    }//GEN-LAST:event_formWindowActivated

    private void jmRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRegresarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jmRegresarMouseClicked

    int id;
    String hrcita, fecha, paciente;
    private DefaultTableModel m;
    private java.sql.Connection cn;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn103;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn113;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn123;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn133;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn163;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn173;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn183;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn193;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn203;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn93;
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdfecha;
    private javax.swing.JMenu jmRegresar;
    private javax.swing.JTable tblcitas;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtpaciente;
    // End of variables declaration//GEN-END:variables
}
