
import clases.Conexion;
import clases.direction;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ana1
 */
public class VerIngresos extends javax.swing.JDialog {

    /**
     * Creates new form VerIngresos
     */
    public VerIngresos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         conectar();
        m=(DefaultTableModel) tblIngresos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIngresos = new javax.swing.JTable();
        jdFecha = new com.toedter.calendar.JDateChooser();
        btnVerCitas = new javax.swing.JButton();
        rbtndia = new javax.swing.JRadioButton();
        rbtnfecha = new javax.swing.JRadioButton();
        jdcdesde = new com.toedter.calendar.JDateChooser();
        jdchasta = new com.toedter.calendar.JDateChooser();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 204), null));

        tblIngresos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Fecha", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngresosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblIngresos);
        if (tblIngresos.getColumnModel().getColumnCount() > 0) {
            tblIngresos.getColumnModel().getColumn(0).setResizable(false);
            tblIngresos.getColumnModel().getColumn(1).setResizable(false);
            tblIngresos.getColumnModel().getColumn(2).setResizable(false);
        }

        jdFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdFechaKeyPressed(evt);
            }
        });

        btnVerCitas.setBackground(new java.awt.Color(255, 255, 255));
        btnVerCitas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnVerCitas.setText("Ver Ingresos");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });

        rbtndia.setBackground(new java.awt.Color(255, 255, 255));
        rbtndia.setText("Dia");
        rbtndia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rbtndiaPropertyChange(evt);
            }
        });

        rbtnfecha.setBackground(new java.awt.Color(255, 255, 255));
        rbtnfecha.setText("Entre fechas");
        rbtnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Ingresos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnfecha)
                                    .addComponent(rbtndia))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jdcdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdchasta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtndia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdchasta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnfecha)
                        .addComponent(jdcdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void conectar(){
        con =  new Conexion();
        cn = con.getConection();
    }
    private void tblIngresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngresosMouseClicked
       
    }//GEN-LAST:event_tblIngresosMouseClicked

    private void jdFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdFechaKeyPressed

    }//GEN-LAST:event_jdFechaKeyPressed
    public void llenartabla(){
        try{
            Statement stmt=cn.createStatement();
            stmt.execute("select*from Movimientos where Fecha=DateValue('"+fecha+"') AND Tipo='Cargo';");
            ResultSet rs=stmt.getResultSet();
            m.setRowCount(0);
            Object  O[]=new Object[3];
            if(rs!=null){
                while(rs.next()){    
                          
                    O[0]=rs.getString("Descripcion");
                    O[1]=rs.getDate("Fecha");
                    O[2]=rs.getFloat("Monto");
                    m.addRow(O);
                }
            }else{
                showMessageDialog(this,"Error");
            }
            stmt.close();
        }catch(SQLException ex){
            showMessageDialog(this,ex.getMessage());
        }
        total();
    }
     public void llenartablames(){
        try{
            Statement stmt=cn.createStatement();
            stmt.execute("select*from Movimientos where Fecha BETWEEN DateValue('"+fechadesde+"') AND DateValue('"+fechahasta+"') AND Tipo='Cargo';");
            ResultSet rs=stmt.getResultSet();
            m.setRowCount(0);
            Object  O[]=new Object[3];
            if(rs!=null){
                while(rs.next()){    
                    O[0]=rs.getString("Descripcion");
                    O[1]=rs.getDate("Fecha");
                    O[2]=rs.getFloat("Monto");
                    m.addRow(O);
                }
            }else{
                showMessageDialog(this,"Error");
            }
            stmt.close();
        }catch(SQLException ex){
            showMessageDialog(this,ex.getMessage());
        }
        total();
    }
     private void total(){
         float total=0;
         for(int i=0;i<tblIngresos.getRowCount();i++)
      {
          total+=Float.parseFloat(tblIngresos.getValueAt(i, 2).toString());
      }
      txttotal.setText(total+"");
     }
    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        try{
            if(rbtndia.isSelected())
            {
                
                fecha=jdFecha.getDate().getDate()+"/"+(jdFecha.getDate().getMonth()+1)+"/"+(jdFecha.getDate().getYear()+1900);
                llenartabla();
            }
            else
            {
                if(rbtnfecha.isSelected())
                {
                    //validar fechas
                    fechadesde=jdcdesde.getDate().getDate()+"/"+(jdcdesde.getDate().getMonth()+1)+"/"+(jdcdesde.getDate().getYear()+1900);
                    fechahasta=jdchasta.getDate().getDate()+"/"+(jdchasta.getDate().getMonth()+1)+"/"+(jdchasta.getDate().getYear()+1900);
                    llenartablames();

                }
                
            }
        }catch(ToothException e){
            showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void rbtndiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rbtndiaPropertyChange

    }//GEN-LAST:event_rbtndiaPropertyChange

    private void rbtnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerIngresos dialog = new VerIngresos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    String fecha;
    String fechadesde,fechahasta;
    private DefaultTableModel m;   
    private java.sql.Connection cn;
    Conexion con;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdFecha;
    private com.toedter.calendar.JDateChooser jdcdesde;
    private com.toedter.calendar.JDateChooser jdchasta;
    private javax.swing.JRadioButton rbtndia;
    private javax.swing.JRadioButton rbtnfecha;
    private javax.swing.JTable tblIngresos;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
