import clases.direction;
import java.sql.*;
import java.util.logging.*;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author SEGsoft
 */
public class vHistorialClinico extends javax.swing.JFrame {

    /**
     * Creates new form vHistorialClinico
     */
    public vHistorialClinico() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Image/Icono1.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTutor = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtOdontologo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtAntec = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCirugias = new javax.swing.JTextField();
        txtTSangre = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsulta = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        rbtnPSi8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbtnPNo8 = new javax.swing.JRadioButton();
        rbtnPSi = new javax.swing.JRadioButton();
        rbtnPNo = new javax.swing.JRadioButton();
        rbtnAnSi = new javax.swing.JRadioButton();
        rbtnAnNo = new javax.swing.JRadioButton();
        rbtnPSi9 = new javax.swing.JRadioButton();
        rbtnPNo9 = new javax.swing.JRadioButton();
        rbtnPSi10 = new javax.swing.JRadioButton();
        rbtnPNo10 = new javax.swing.JRadioButton();
        rbtnYSi = new javax.swing.JRadioButton();
        rbtnPSi11 = new javax.swing.JRadioButton();
        rbtnYNo = new javax.swing.JRadioButton();
        rbtnPNo11 = new javax.swing.JRadioButton();
        rbtnASi = new javax.swing.JRadioButton();
        rbtnPNo12 = new javax.swing.JRadioButton();
        rbtnANo = new javax.swing.JRadioButton();
        rbtnPSi12 = new javax.swing.JRadioButton();
        txtotro = new javax.swing.JTextField();
        rbtnPNo13 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbtnPSi13 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rbtnPSi1 = new javax.swing.JRadioButton();
        rbtnPNo1 = new javax.swing.JRadioButton();
        rbtnPSi2 = new javax.swing.JRadioButton();
        rbtnPNo2 = new javax.swing.JRadioButton();
        rbtnPSi3 = new javax.swing.JRadioButton();
        rbtnPNo3 = new javax.swing.JRadioButton();
        rbtnPNo14 = new javax.swing.JRadioButton();
        rbtnPSi14 = new javax.swing.JRadioButton();
        rbtnPNo15 = new javax.swing.JRadioButton();
        rbtnPSi15 = new javax.swing.JRadioButton();
        rbtnPNo16 = new javax.swing.JRadioButton();
        rbtnPSi16 = new javax.swing.JRadioButton();
        rbtnPSi4 = new javax.swing.JRadioButton();
        rbtnPNo4 = new javax.swing.JRadioButton();
        rbtnPSi5 = new javax.swing.JRadioButton();
        rbtnPNo5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbtnPSi6 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtnPNo6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnPSi7 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbtnPNo7 = new javax.swing.JRadioButton();
        rbtnPNo17 = new javax.swing.JRadioButton();
        rbtnPSi17 = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        txtfechanac = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ToothCenter - Historial Clinico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Historia clinica odontologica");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(514, 514, 514)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel18.setText("Fecha");

        txtFecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFecha.setEnabled(false);

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setText("Edad");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel21.setText("Sexo");

        txtEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEdad.setEnabled(false);

        txtSexo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSexo.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel22.setText("Padre o tutor");

        txtTutor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTutor.setEnabled(false);
        txtTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTutorActionPerformed(evt);
            }
        });

        txtDomicilio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDomicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDomicilio.setEnabled(false);
        txtDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel23.setText("Domicilio");

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel24.setText("Fecha de nacimiento");

        txtOdontologo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtOdontologo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOdontologo.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel25.setText("Odontologo tratante");

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel26.setText("Antecedentes familiares");

        txtAntec.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAntec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAntec.setEnabled(false);

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel27.setText("Tension arterial");

        txtTA.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTA.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel28.setText("Cirugías");

        txtCirugias.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCirugias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCirugias.setEnabled(false);
        txtCirugias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCirugiasActionPerformed(evt);
            }
        });

        txtTSangre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTSangre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTSangre.setEnabled(false);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel29.setText("Transfuciones de sangre");

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel30.setText("Motivo de consulta");

        txtConsulta.setColumns(20);
        txtConsulta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtConsulta.setRows(5);
        txtConsulta.setEnabled(false);
        jScrollPane3.setViewportView(txtConsulta);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Aspirina");

        rbtnPSi8.setText("Si");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Otro");

        rbtnPNo8.setText("No");

        rbtnPSi.setText("Si");

        rbtnPNo.setText("No");

        rbtnAnSi.setText("Si");

        rbtnAnNo.setText("No");

        rbtnPSi9.setText("Si");

        rbtnPNo9.setText("No");

        rbtnPSi10.setText("Si");

        rbtnPNo10.setText("No");

        rbtnYSi.setText("Si");

        rbtnPSi11.setText("Si");

        rbtnYNo.setText("No");

        rbtnPNo11.setText("No");

        rbtnASi.setText("Si");

        rbtnPNo12.setText("No");

        rbtnANo.setText("No");

        rbtnPSi12.setText("Si");

        txtotro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtotro.setEnabled(false);

        rbtnPNo13.setText("No");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Padecimientos");

        rbtnPSi13.setText("Si");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Alta o baja presión");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Sangre excesiva al cortarse");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Problemas sanguineos");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("V.I.H. Positivo");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Consumo de medicamentos retroviales");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Embarazada");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Consumo de pastillas anticonceptivas");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Enfermedades venereas");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Hepatitis");

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel31.setText("Ulcera gastrica");

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel32.setText("Asma");

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel33.setText("Fiebre reumatica");

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel34.setText("Tiroides");

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel35.setText("Diabetes");

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel36.setText("Ruidos en la mandibula");

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel37.setText("Aftas recurrentes");

        rbtnPSi1.setText("Si");

        rbtnPNo1.setText("No");

        rbtnPSi2.setText("Si");

        rbtnPNo2.setText("No");

        rbtnPSi3.setText("Si");

        rbtnPNo3.setText("No");

        rbtnPNo14.setText("No");

        rbtnPSi14.setText("Si");

        rbtnPNo15.setText("No");

        rbtnPSi15.setText("Si");

        rbtnPNo16.setText("No");

        rbtnPSi16.setText("Si");

        rbtnPSi4.setText("Si");

        rbtnPNo4.setText("No");

        rbtnPSi5.setText("Si");

        rbtnPNo5.setText("No");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel1.setText("Alergias");

        rbtnPSi6.setText("Si");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Penicilina");

        rbtnPNo6.setText("No");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Anestecia");

        rbtnPSi7.setText("Si");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Yodo");

        rbtnPNo7.setText("No");

        rbtnPNo17.setText("No");

        rbtnPSi17.setText("Si");

        jLabel38.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel38.setText("Limitaciones para abrir la boca");

        txtfechanac.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtfechanac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfechanac.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(24, 24, 24)
                                .addComponent(txtTSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(143, 143, 143)
                                .addComponent(txtCirugias, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(86, 86, 86)
                                .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(24, 24, 24)
                                .addComponent(txtAntec, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(56, 56, 56)
                                        .addComponent(rbtnPSi1)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo1))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(8, 8, 8)
                                        .addComponent(rbtnPSi2)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo2))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(36, 36, 36)
                                        .addComponent(rbtnPSi3)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo3))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(81, 81, 81)
                                        .addComponent(rbtnPSi4)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo4))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(109, 109, 109)
                                        .addComponent(rbtnPSi5)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo5))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(89, 89, 89)
                                        .addComponent(rbtnPSi6)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo6))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(25, 25, 25)
                                        .addComponent(rbtnPSi7)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(119, 119, 119)
                                        .addComponent(rbtnPSi12)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo12))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(100, 100, 100)
                                        .addComponent(rbtnPSi13)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo13))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addGap(52, 52, 52)
                                        .addComponent(rbtnPSi14)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo14))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(106, 106, 106)
                                        .addComponent(rbtnPSi15)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo15))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(54, 54, 54)
                                        .addComponent(rbtnPSi11)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo11))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(21, 21, 21)
                                        .addComponent(rbtnPSi16)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo16)))
                                .addGap(64, 64, 64))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addComponent(jLabel1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(rbtnPSi)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnPNo))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(rbtnAnSi)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAnNo))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(rbtnYSi)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnYNo))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)
                                .addComponent(rbtnASi)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnANo))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(txtotro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel31)
                                .addGap(75, 75, 75)
                                .addComponent(rbtnPSi8)
                                .addGap(17, 17, 17)
                                .addComponent(rbtnPNo8))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel14)
                                .addGap(13, 13, 13)
                                .addComponent(rbtnPSi9)
                                .addGap(17, 17, 17)
                                .addComponent(rbtnPNo9))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel38))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(rbtnPSi17)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo17))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(rbtnPSi10)
                                        .addGap(17, 17, 17)
                                        .addComponent(rbtnPNo10)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(310, 310, 310))))
            .addComponent(jSeparator1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(rbtnPSi)
                            .addComponent(rbtnPNo))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addComponent(rbtnAnSi)
                            .addComponent(rbtnAnNo))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbtnYSi)
                            .addComponent(rbtnYNo))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbtnASi)
                            .addComponent(rbtnANo))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(txtotro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtOdontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(txtAntec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCirugias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(txtTSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel30))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(rbtnPSi1)
                                            .addComponent(rbtnPNo1)
                                            .addComponent(jLabel33)
                                            .addComponent(rbtnPSi11)
                                            .addComponent(rbtnPNo11))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(rbtnPSi2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtnPNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel32)
                                            .addComponent(rbtnPSi12)
                                            .addComponent(rbtnPNo12))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(rbtnPSi3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtnPNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35)
                                            .addComponent(rbtnPSi13)
                                            .addComponent(rbtnPNo13))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(rbtnPSi4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtnPNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel37)
                                            .addComponent(rbtnPSi14)
                                            .addComponent(rbtnPNo14))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(rbtnPSi5)
                                            .addComponent(rbtnPNo5)
                                            .addComponent(jLabel34)
                                            .addComponent(rbtnPSi15)
                                            .addComponent(rbtnPNo15))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(rbtnPSi6)
                                            .addComponent(rbtnPNo6)
                                            .addComponent(jLabel36)
                                            .addComponent(rbtnPSi16)
                                            .addComponent(rbtnPNo16))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(rbtnPSi7)
                                            .addComponent(rbtnPNo7))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(rbtnPSi8)
                                            .addComponent(rbtnPNo8))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel14))
                                            .addComponent(rbtnPSi9)
                                            .addComponent(rbtnPNo9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(rbtnPSi10)
                                            .addComponent(rbtnPNo10))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnPSi17)
                                            .addComponent(rbtnPNo17)))
                                    .addComponent(jLabel38)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(67, 67, 67))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jMenu1.setToolTipText("Regresar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCirugiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCirugiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCirugiasActionPerformed

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void txtTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTutorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        llenarcampos();
    }//GEN-LAST:event_formWindowActivated

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked
int id;
    public void llenarcampos()
    {
        try{
            Statement stmt=cn.createStatement();
            stmt.execute("select*from HistorialClinico where idPaciente="+id);
            ResultSet rs=stmt.getResultSet();
            
            if(rs!=null)
            {
                while(rs.next()){
                   txtFecha.setText(rs.getDate("Fecha").toString());
                  txtTutor.setText(rs.getString("Tutor"));
                  txtfechanac.setText(rs.getDate("FechaNacimiento").toString());
                 txtOdontologo.setText(rs.getString("Odontologo"));
                 txtAntec.setText(rs.getString("Antecedentes"));
                 txtTA.setText(rs.getString("Tension"));
                 txtCirugias.setText(rs.getString("Cirugias"));
                 txtTSangre.setText(rs.getString("Transfuciones"));
                 txtConsulta.setText(rs.getString("Motivo"));
                 
                 if(rs.getString("Penicilina").equals("Si"))
                 {rbtnPSi.setSelected(true);}else{rbtnPNo.setSelected(true);}
                  
                 if(rs.getString("Anestecia").equals("Si"))
                 {rbtnAnSi.setSelected(true);}else{rbtnAnNo.setSelected(true);}
                 
                 if(rs.getString("Yodo").equals("Si"))
                 {rbtnYSi.setSelected(true);}else{rbtnYNo.setSelected(true);}
                 
                 if(rs.getString("Aspirina").equals("Si"))
                 {rbtnASi.setSelected(true);}else{rbtnANo.setSelected(true);}
                 
                 if(rs.getString("Penicilina").equals("Si"))
                 {rbtnPSi.setSelected(true);}else{rbtnPNo.setSelected(true);}
                 
                 txtotro.setText(rs.getString("Otro"));
                 
                 if(rs.getString("Altapresion").equals("Si"))
                 {rbtnPSi1.setSelected(true);}else{rbtnPNo1.setSelected(true);}
                
                 if(rs.getString("SangreExcesiva").equals("Si"))
                 {rbtnPSi2.setSelected(true);}else{rbtnPNo2.setSelected(true);}
                 
                 if(rs.getString("ProblemasSanguineos").equals("Si"))
                 {rbtnPSi3.setSelected(true);}else{rbtnPNo3.setSelected(true);}
                 
                 if(rs.getString("VIH").equals("Si"))
                 {rbtnPSi4.setSelected(true);}else{rbtnPNo4.setSelected(true);}
                 
                 if(rs.getString("Hepatitis").equals("Si"))
                 {rbtnPSi5.setSelected(true);}else{rbtnPNo5.setSelected(true);}
                 
                 if(rs.getString("Embarazo").equals("Si"))
                 {rbtnPSi6.setSelected(true);}else{rbtnPNo6.setSelected(true);}
                 
                 if(rs.getString("EnfermedadesVenereas").equals("Si"))
                 {rbtnPSi7.setSelected(true);}else{rbtnPNo7.setSelected(true);}
                 
                 if(rs.getString("UlceraGastrica").equals("Si"))
                 {rbtnPSi8.setSelected(true);}else{rbtnPNo8.setSelected(true);}
                 
                 if(rs.getString("PastillasAnticonceptivas").equals("Si"))
                 {rbtnPSi9.setSelected(true);}else{rbtnPNo9.setSelected(true);}
                 
                 if(rs.getString("MedicamentosRetroviales").equals("Si"))
                 {rbtnPSi10.setSelected(true);}else{rbtnPNo10.setSelected(true);}
                 
                 if(rs.getString("LimitacionesBoca").equals("Si"))
                 {rbtnPSi17.setSelected(true);}else{rbtnPNo17.setSelected(true);}
                 
                 if(rs.getString("FiebreReumatica").equals("Si"))
                 {rbtnPSi11.setSelected(true);}else{rbtnPNo11.setSelected(true);}
                 
                 if(rs.getString("Asma").equals("Si"))
                 {rbtnPSi12.setSelected(true);}else{rbtnPNo12.setSelected(true);}
                 
                 if(rs.getString("Diabetes").equals("Si"))
                 {rbtnPSi13.setSelected(true);}else{rbtnPNo13.setSelected(true);}
                 
                 if(rs.getString("AftasRecurrentes").equals("Si"))
                 {rbtnPSi14.setSelected(true);}else{rbtnPNo14.setSelected(true);}
                 
                 if(rs.getString("Tiroides").equals("Si"))
                 {rbtnPSi15.setSelected(true);}else{rbtnPNo15.setSelected(true);}
                 
                 if(rs.getString("RuidosMandibula").equals("Si"))
                 {rbtnPSi16.setSelected(true);}else{rbtnPNo16.setSelected(true);}
                 
                }
            }else{showMessageDialog(this,"Error");}
            stmt.close();
        }catch(SQLException ex){showMessageDialog(this,ex.getMessage());}
        
        
        
        try{
        
            Statement stmt=cn.createStatement();
            stmt.execute("select*from Paciente where Id="+id);
            ResultSet rs=stmt.getResultSet();
            
            
            if(rs!=null)
            {
                while(rs.next()){    
                  txtNombre.setText(rs.getString("Nombre"));
                  txtEdad.setText(rs.getInt("Edad")+"");
                  txtSexo.setText(rs.getString("Sexo"));
                  txtTutor.setText(rs.getString("Tutor"));
                  txtDomicilio.setText(rs.getString("Domicilio"));
                }
            }else{showMessageDialog(this,"No hay");}
            stmt.close();
            
        }catch(SQLException ex){showMessageDialog(this,ex.getMessage());}
    }
     private void conectar(){
        direction dir = new direction();
        dir.readTxt("C:\\dir.ini");
        String dbURL="jdbc:ucanaccess://"+dir.getDir();
        try {
            cn=DriverManager.getConnection(dbURL,"","");
            System.out.println("Conectado");
        } catch (SQLException ex) {
            Logger.getLogger(nPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vHistorialClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vHistorialClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vHistorialClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vHistorialClinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vHistorialClinico().setVisible(true);
            }
        });
    }
private java.sql.Connection cn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnANo;
    private javax.swing.JRadioButton rbtnASi;
    private javax.swing.JRadioButton rbtnAnNo;
    private javax.swing.JRadioButton rbtnAnSi;
    private javax.swing.JRadioButton rbtnPNo;
    private javax.swing.JRadioButton rbtnPNo1;
    private javax.swing.JRadioButton rbtnPNo10;
    private javax.swing.JRadioButton rbtnPNo11;
    private javax.swing.JRadioButton rbtnPNo12;
    private javax.swing.JRadioButton rbtnPNo13;
    private javax.swing.JRadioButton rbtnPNo14;
    private javax.swing.JRadioButton rbtnPNo15;
    private javax.swing.JRadioButton rbtnPNo16;
    private javax.swing.JRadioButton rbtnPNo17;
    private javax.swing.JRadioButton rbtnPNo2;
    private javax.swing.JRadioButton rbtnPNo3;
    private javax.swing.JRadioButton rbtnPNo4;
    private javax.swing.JRadioButton rbtnPNo5;
    private javax.swing.JRadioButton rbtnPNo6;
    private javax.swing.JRadioButton rbtnPNo7;
    private javax.swing.JRadioButton rbtnPNo8;
    private javax.swing.JRadioButton rbtnPNo9;
    private javax.swing.JRadioButton rbtnPSi;
    private javax.swing.JRadioButton rbtnPSi1;
    private javax.swing.JRadioButton rbtnPSi10;
    private javax.swing.JRadioButton rbtnPSi11;
    private javax.swing.JRadioButton rbtnPSi12;
    private javax.swing.JRadioButton rbtnPSi13;
    private javax.swing.JRadioButton rbtnPSi14;
    private javax.swing.JRadioButton rbtnPSi15;
    private javax.swing.JRadioButton rbtnPSi16;
    private javax.swing.JRadioButton rbtnPSi17;
    private javax.swing.JRadioButton rbtnPSi2;
    private javax.swing.JRadioButton rbtnPSi3;
    private javax.swing.JRadioButton rbtnPSi4;
    private javax.swing.JRadioButton rbtnPSi5;
    private javax.swing.JRadioButton rbtnPSi6;
    private javax.swing.JRadioButton rbtnPSi7;
    private javax.swing.JRadioButton rbtnPSi8;
    private javax.swing.JRadioButton rbtnPSi9;
    private javax.swing.JRadioButton rbtnYNo;
    private javax.swing.JRadioButton rbtnYSi;
    private javax.swing.JTextField txtAntec;
    private javax.swing.JTextField txtCirugias;
    private javax.swing.JTextArea txtConsulta;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOdontologo;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTA;
    private javax.swing.JTextField txtTSangre;
    private javax.swing.JTextField txtTutor;
    private javax.swing.JTextField txtfechanac;
    private javax.swing.JTextField txtotro;
    // End of variables declaration//GEN-END:variables
}
